import OpenAI from 'openai';

// ========== TYPE DEFINITIONS ==========

/**
 * Represents the conversational context collected from the user during onboarding
 * This is the Q&A data that the coach uses to generate a habit plan
 */
export interface OnboardingCoachContext {
  // Question 1: Identity
  desiredIdentity?: string;

  // Question 2: Habit idea
  habitIdea?: string;

  // Question 3: When in the day
  whenInDay?: string;

  // Question 4: Where
  whereLocation?: string;

  // Question 5: What makes it enjoyable/obvious
  whatMakesItEnjoyable?: string;

  // Optional: User's name
  userName?: string;
}

/**
 * The structured habit plan generated by the coach
 * This will auto-populate the onboarding form
 */
export interface HabitPlan {
  identity: string;
  habitName: string;
  tinyVersion: string;
  implementationTime: string;  // HH:MM format
  implementationLocation: string;
  temptationBundle?: string;
  preHabitRitual?: string;
  environmentCue?: string;
  environmentDistraction?: string;
}

/**
 * Metadata about the habit plan generation
 * Helps the client handle partial/incomplete plans
 */
export interface HabitPlanMetadata {
  confidence: number;  // 0-1 scale
  missingFields?: string[];
  notes?: string;
}

/**
 * Complete result returned to the client
 */
export interface HabitPlanResult {
  habitPlan: HabitPlan;
  metadata: HabitPlanMetadata;
}

// ========== HEURISTIC HABIT PLAN (FALLBACK) ==========

/**
 * Generate a basic habit plan using heuristic logic from the conversation context
 * This is the fallback when OpenAI is unavailable or fails
 */
function generateHeuristicHabitPlan(context: OnboardingCoachContext): HabitPlanResult {
  console.log('🔄 Generating heuristic habit plan from context');

  // Extract and normalize fields
  const identity = normalizeIdentity(context.desiredIdentity || '');
  const habitName = normalizeHabitName(context.habitIdea || '');
  const tinyVersion = generateTinyVersion(habitName);
  const implementationTime = normalizeTime(context.whenInDay || '');
  const implementationLocation = normalizeLocation(context.whereLocation || '');

  // Generate optional fields based on context
  const temptationBundle = inferTemptationBundle(
    habitName,
    context.whatMakesItEnjoyable || '',
    implementationTime
  );
  const preHabitRitual = inferPreHabitRitual(habitName);
  const environmentCue = inferEnvironmentCue(habitName, implementationLocation, implementationTime);
  const environmentDistraction = inferEnvironmentDistraction(habitName);

  // Check for missing required fields
  const missingFields: string[] = [];
  if (!identity || identity.length < 5) missingFields.push('identity');
  if (!habitName || habitName.length < 3) missingFields.push('habit_name');
  if (!tinyVersion) missingFields.push('tiny_version');
  if (!implementationTime.match(/^\d{2}:\d{2}$/)) missingFields.push('implementation_time');
  if (!implementationLocation || implementationLocation.length < 3) missingFields.push('implementation_location');

  // Calculate confidence
  const confidence = missingFields.length === 0 ? 0.7 : 0.4;

  return {
    habitPlan: {
      identity,
      habitName,
      tinyVersion,
      implementationTime,
      implementationLocation,
      temptationBundle: temptationBundle || undefined,
      preHabitRitual: preHabitRitual || undefined,
      environmentCue: environmentCue || undefined,
      environmentDistraction: environmentDistraction || undefined,
    },
    metadata: {
      confidence,
      missingFields: missingFields.length > 0 ? missingFields : undefined,
      notes: missingFields.length > 0
        ? 'Some details need manual completion. Fill in the highlighted fields.'
        : 'Heuristic plan generated. Feel free to refine before saving.',
    },
  };
}

// ========== HEURISTIC HELPER FUNCTIONS ==========

function normalizeIdentity(input: string): string {
  const lower = input.toLowerCase().trim();

  // If user says "I want to be a reader", extract "a reader"
  if (lower.includes('want to be') || lower.includes('want to become')) {
    const match = lower.match(/(?:want to (?:be|become)\s+)(.+)/);
    if (match) return `I am ${match[1]}`.trim();
  }

  // If user says "a healthy person", add "I am"
  if (!lower.startsWith('i am') && !lower.startsWith('i\'m')) {
    return `I am ${input.trim()}`;
  }

  return input.trim();
}

function normalizeHabitName(input: string): string {
  const lower = input.toLowerCase().trim();

  // Extract core habit from longer phrases
  // e.g., "I want to read more" → "Read every day"
  if (lower.includes('read')) {
    return 'Read every day';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Write in my journal';
  } else if (lower.includes('exercise') || lower.includes('workout')) {
    return 'Exercise';
  } else if (lower.includes('meditate')) {
    return 'Meditate';
  } else if (lower.includes('walk')) {
    return 'Go for a walk';
  } else if (lower.includes('run')) {
    return 'Go for a run';
  }

  return input.trim() || 'Build a new habit';
}

function generateTinyVersion(habitName: string): string {
  const lower = habitName.toLowerCase();

  if (lower.includes('read')) {
    return 'Read one page';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Write one sentence';
  } else if (lower.includes('exercise') || lower.includes('workout')) {
    return 'Do 5 pushups';
  } else if (lower.includes('meditate')) {
    return 'Meditate for 1 minute';
  } else if (lower.includes('walk')) {
    return 'Walk for 2 minutes';
  } else if (lower.includes('run')) {
    return 'Put on running shoes and step outside';
  }

  return `Start ${habitName.toLowerCase()} for 2 minutes`;
}

function normalizeTime(input: string): string {
  const lower = input.toLowerCase().trim();

  // Try to extract HH:MM format
  const timeMatch = input.match(/(\d{1,2}):(\d{2})/);
  if (timeMatch) {
    const hour = parseInt(timeMatch[1], 10);
    const minute = parseInt(timeMatch[2], 10);
    return `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
  }

  // Parse natural language time
  if (lower.includes('morning') || lower.includes('wake up') || lower.includes('breakfast')) {
    return '07:00';
  } else if (lower.includes('lunch') || lower.includes('noon') || lower.includes('midday')) {
    return '12:00';
  } else if (lower.includes('afternoon')) {
    return '15:00';
  } else if (lower.includes('evening') || lower.includes('dinner')) {
    return '18:00';
  } else if (lower.includes('night') || lower.includes('bed') || lower.includes('sleep')) {
    return '21:00';
  }

  // Default to evening
  return '19:00';
}

function normalizeLocation(input: string): string {
  const lower = input.toLowerCase().trim();

  if (!input || input.length < 2) {
    return 'At home';
  }

  // Add "at" or "in" if missing
  if (!lower.startsWith('at ') && !lower.startsWith('in ') && !lower.startsWith('on ')) {
    return `At ${input.trim()}`;
  }

  return input.trim();
}

function inferTemptationBundle(habitName: string, enjoyableContext: string, time: string): string | null {
  const lower = habitName.toLowerCase();
  const enjoyLower = enjoyableContext.toLowerCase();

  // If user mentioned something enjoyable, use it
  if (enjoyLower.includes('coffee') || enjoyLower.includes('tea')) {
    return `Have ${enjoyLower.includes('coffee') ? 'coffee' : 'tea'} while doing this`;
  }
  if (enjoyLower.includes('music')) {
    return 'Listen to your favorite music';
  }
  if (enjoyLower.includes('podcast')) {
    return 'Listen to a podcast';
  }

  // Default suggestions based on habit
  if (lower.includes('read')) {
    return time >= '18:00' ? 'Have herbal tea while reading' : 'Have coffee while reading';
  } else if (lower.includes('exercise') || lower.includes('walk')) {
    return 'Listen to your favorite podcast';
  } else if (lower.includes('write')) {
    return 'Light a candle and play soft music';
  }

  return null;
}

function inferPreHabitRitual(habitName: string): string | null {
  const lower = habitName.toLowerCase();

  if (lower.includes('read')) {
    return 'Take 3 deep breaths and open your book';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Put your phone on Do Not Disturb';
  } else if (lower.includes('exercise')) {
    return 'Put on your workout clothes immediately';
  } else if (lower.includes('meditate')) {
    return 'Close your eyes and take 3 deep breaths';
  }

  return 'Take 3 slow, deep breaths';
}

function inferEnvironmentCue(habitName: string, location: string, time: string): string | null {
  const lower = habitName.toLowerCase();
  const locationLower = location.toLowerCase();

  if (lower.includes('read')) {
    if (locationLower.includes('bed')) {
      return `Put your book on your pillow at ${time}`;
    }
    return 'Place your book where you can\'t miss it';
  } else if (lower.includes('exercise') || lower.includes('walk')) {
    return 'Lay out your workout clothes the night before';
  } else if (lower.includes('write')) {
    return 'Leave your journal open with a pen on top';
  }

  return `Place a visual reminder in ${location}`;
}

function inferEnvironmentDistraction(habitName: string): string | null {
  const lower = habitName.toLowerCase();

  if (lower.includes('read') || lower.includes('write') || lower.includes('meditate')) {
    return 'Charge your phone in another room';
  } else if (lower.includes('exercise')) {
    return 'Put your phone on Do Not Disturb mode';
  }

  return 'Put your phone in another room';
}

// ========== LLM INTEGRATION WITH FALLBACK ==========

/**
 * Generate onboarding habit plan using OpenAI LLM, with automatic fallback to heuristics
 *
 * Behavior:
 * 1. If OPENAI_API_KEY is not set → use heuristics immediately
 * 2. If OPENAI_API_KEY is set → try LLM with 5s timeout
 * 3. If LLM fails (network, timeout, invalid response) → fall back to heuristics
 *
 * Guarantees: Always returns a HabitPlanResult with at least basic fields
 */
export async function generateOnboardingHabitPlan(
  context: OnboardingCoachContext
): Promise<HabitPlanResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  // No API key → use heuristics immediately
  if (!apiKey) {
    console.warn('⚠️  OPENAI_API_KEY not set – using heuristic habit plan generation');
    return generateHeuristicHabitPlan(context);
  }

  // Try LLM with timeout
  try {
    console.log(`🤖 Attempting OpenAI LLM call for coach onboarding...`);

    const result = await Promise.race([
      callOpenAI(apiKey, context),
      createTimeout(5000, 'OpenAI request timeout after 5s')
    ]);

    // Validate LLM response
    if (result && result.habitPlan && result.habitPlan.habitName && result.habitPlan.tinyVersion) {
      console.log(`✅ OpenAI returned habit plan for "${result.habitPlan.habitName}"`);
      return result;
    } else {
      console.error('❌ OpenAI returned invalid habit plan structure, using fallback');
      return generateHeuristicHabitPlan(context);
    }
  } catch (error) {
    console.error('❌ OpenAI call failed:', error instanceof Error ? error.message : String(error));
    console.log('🔄 Falling back to heuristic habit plan generation');
    return generateHeuristicHabitPlan(context);
  }
}

/**
 * Call OpenAI API to generate habit plan from conversational context
 */
async function callOpenAI(
  apiKey: string,
  context: OnboardingCoachContext
): Promise<HabitPlanResult> {
  const openai = new OpenAI({ apiKey });

  // Build prompt
  const prompt = buildPrompt(context);

  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'system',
        content: `You are an expert Atomic Habits coach helping someone design their first tiny habit during onboarding.
Your role is to synthesize the conversational context into a complete, structured habit plan.

Key principles:
- Identity-first: Frame habits as "I am [identity]" not "I want to be"
- 2-minute rule: Make the tiny version so easy they can't say no
- Implementation intention: Specific time and place
- Make it obvious: Clear environmental cues
- Make it attractive: Temptation bundling
- Make it easy: Remove friction and distractions

Always respond with valid JSON only.`
      },
      {
        role: 'user',
        content: prompt
      }
    ],
    temperature: 0.7,
    max_tokens: 600,
    response_format: { type: 'json_object' }
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error('OpenAI returned empty response');
  }

  // Parse and validate JSON
  const parsed = JSON.parse(content);

  if (!parsed.habit_plan) {
    throw new Error('OpenAI response missing "habit_plan" object');
  }

  const plan = parsed.habit_plan;

  // Validate required fields
  if (!plan.identity || !plan.habit_name || !plan.tiny_version ||
      !plan.implementation_time || !plan.implementation_location) {
    throw new Error('OpenAI habit plan missing required fields');
  }

  // Validate time format (HH:MM)
  if (!plan.implementation_time.match(/^\d{2}:\d{2}$/)) {
    throw new Error('Invalid implementation_time format (expected HH:MM)');
  }

  // Build metadata
  const missingFields: string[] = [];
  if (!plan.temptation_bundle) missingFields.push('temptation_bundle');
  if (!plan.pre_habit_ritual) missingFields.push('pre_habit_ritual');
  if (!plan.environment_cue) missingFields.push('environment_cue');
  if (!plan.environment_distraction) missingFields.push('environment_distraction');

  const metadata: HabitPlanMetadata = {
    confidence: parsed.metadata?.confidence || 0.85,
    missingFields: missingFields.length > 0 ? missingFields : undefined,
    notes: parsed.metadata?.notes || 'AI-generated plan. Review and adjust as needed.',
  };

  return {
    habitPlan: {
      identity: plan.identity.trim(),
      habitName: plan.habit_name.trim(),
      tinyVersion: plan.tiny_version.trim(),
      implementationTime: plan.implementation_time.trim(),
      implementationLocation: plan.implementation_location.trim(),
      temptationBundle: plan.temptation_bundle?.trim() || undefined,
      preHabitRitual: plan.pre_habit_ritual?.trim() || undefined,
      environmentCue: plan.environment_cue?.trim() || undefined,
      environmentDistraction: plan.environment_distraction?.trim() || undefined,
    },
    metadata,
  };
}

/**
 * Build the prompt for OpenAI coach onboarding
 */
function buildPrompt(context: OnboardingCoachContext): string {
  return `You are helping ${context.userName || 'a new user'} design their first Atomic Habit.
Based on the conversation, generate a complete habit plan.

CONVERSATION CONTEXT:

Q: "What type of person are you trying to become?"
A: ${context.desiredIdentity || 'Not provided'}

Q: "What's one small habit that would support that?"
A: ${context.habitIdea || 'Not provided'}

Q: "When in your day does this realistically fit?"
A: ${context.whenInDay || 'Not provided'}

Q: "Where will you usually be when doing it?"
A: ${context.whereLocation || 'Not provided'}

Q: "What would make this more enjoyable or obvious?"
A: ${context.whatMakesItEnjoyable || 'Not provided'}

TASK:
Generate a structured habit plan with ALL of the following fields:

Required fields:
- identity: Identity statement in "I am [identity]" format (not "I want to be")
- habit_name: Clear habit name (e.g., "Read every day", "Exercise")
- tiny_version: 2-minute version so easy they can't say no (e.g., "Read one page")
- implementation_time: HH:MM format (e.g., "07:00", "21:30")
- implementation_location: Specific place (e.g., "In bed", "At my desk")

Optional fields (include if you can infer from context):
- temptation_bundle: Pair habit with something enjoyable (e.g., "Have coffee while reading")
- pre_habit_ritual: 10-30 second ritual to start (e.g., "Take 3 deep breaths")
- environment_cue: Visual trigger in the environment (e.g., "Put book on pillow at 21:45")
- environment_distraction: Friction to remove (e.g., "Charge phone in another room")

Return ONLY valid JSON in this exact format:
{
  "habit_plan": {
    "identity": "I am a reader",
    "habit_name": "Read every day",
    "tiny_version": "Read one page",
    "implementation_time": "21:00",
    "implementation_location": "In bed",
    "temptation_bundle": "Have herbal tea while reading",
    "pre_habit_ritual": "Take 3 deep breaths and open book",
    "environment_cue": "Put book on pillow at 20:45",
    "environment_distraction": "Charge phone in the kitchen"
  },
  "metadata": {
    "confidence": 0.9,
    "notes": "Great plan! Review and adjust before saving."
  }
}

Make the plan:
- Specific and actionable
- Tailored to the user's context
- Aligned with Atomic Habits principles
- Encouraging and realistic`;
}

/**
 * Create a timeout promise that rejects after specified milliseconds
 */
function createTimeout(ms: number, message: string): Promise<never> {
  return new Promise((_, reject) => {
    setTimeout(() => reject(new Error(message)), ms);
  });
}
