import OpenAI from 'openai';

// ========== TYPE DEFINITIONS ==========

/**
 * Represents the conversational context collected from the user during onboarding
 * This is the Q&A data that the coach uses to generate a habit plan
 */
export interface OnboardingCoachContext {
  // Question 1: Identity
  desiredIdentity?: string;

  // Question 2: Habit idea
  habitIdea?: string;

  // Question 3: When in the day
  whenInDay?: string;

  // Question 4: Where
  whereLocation?: string;

  // Question 5: What makes it enjoyable/obvious
  whatMakesItEnjoyable?: string;

  // Optional: User's name
  userName?: string;
}

/**
 * The structured habit plan generated by the coach
 * This will auto-populate the onboarding form
 */
export interface HabitPlan {
  identity: string;
  habitName: string;
  tinyVersion: string;
  implementationTime: string;  // HH:MM format
  implementationLocation: string;
  temptationBundle?: string;
  preHabitRitual?: string;
  environmentCue?: string;
  environmentDistraction?: string;
}

/**
 * Metadata about the habit plan generation
 * Helps the client handle partial/incomplete plans
 */
export interface HabitPlanMetadata {
  confidence: number;  // 0-1 scale
  missingFields?: string[];
  notes?: string;
}

/**
 * Complete result returned to the client
 */
export interface HabitPlanResult {
  habitPlan: HabitPlan;
  metadata: HabitPlanMetadata;
}

// ========== HEURISTIC HABIT PLAN (FALLBACK) ==========

/**
 * Generate a basic habit plan using heuristic logic from the conversation context
 * This is the fallback when OpenAI is unavailable or fails
 */
function generateHeuristicHabitPlan(context: OnboardingCoachContext): HabitPlanResult {
  console.log('🔄 Generating heuristic habit plan from context');

  // Extract and normalize fields
  const identity = normalizeIdentity(context.desiredIdentity || '');
  const habitName = normalizeHabitName(context.habitIdea || '');
  const tinyVersion = generateTinyVersion(habitName);
  const implementationTime = normalizeTime(context.whenInDay || '');
  const implementationLocation = normalizeLocation(context.whereLocation || '');

  // Generate optional fields based on context
  const temptationBundle = inferTemptationBundle(
    habitName,
    context.whatMakesItEnjoyable || '',
    implementationTime
  );
  const preHabitRitual = inferPreHabitRitual(habitName);
  const environmentCue = inferEnvironmentCue(habitName, implementationLocation, implementationTime);
  const environmentDistraction = inferEnvironmentDistraction(habitName);

  // Check for missing required fields
  const missingFields: string[] = [];
  if (!identity || identity.length < 5) missingFields.push('identity');
  if (!habitName || habitName.length < 3) missingFields.push('habit_name');
  if (!tinyVersion) missingFields.push('tiny_version');
  if (!implementationTime.match(/^\d{2}:\d{2}$/)) missingFields.push('implementation_time');
  if (!implementationLocation || implementationLocation.length < 3) missingFields.push('implementation_location');

  // Calculate confidence
  const confidence = missingFields.length === 0 ? 0.7 : 0.4;

  return {
    habitPlan: {
      identity,
      habitName,
      tinyVersion,
      implementationTime,
      implementationLocation,
      temptationBundle: temptationBundle || undefined,
      preHabitRitual: preHabitRitual || undefined,
      environmentCue: environmentCue || undefined,
      environmentDistraction: environmentDistraction || undefined,
    },
    metadata: {
      confidence,
      missingFields: missingFields.length > 0 ? missingFields : undefined,
      notes: missingFields.length > 0
        ? 'Some details need manual completion. Fill in the highlighted fields.'
        : 'Heuristic plan generated. Feel free to refine before saving.',
    },
  };
}

// ========== HEURISTIC HELPER FUNCTIONS ==========

function normalizeIdentity(input: string): string {
  const lower = input.toLowerCase().trim();

  // If user says "I want to be a reader", extract "a reader"
  if (lower.includes('want to be') || lower.includes('want to become')) {
    const match = lower.match(/(?:want to (?:be|become)\s+)(.+)/);
    if (match) return `I am ${match[1]}`.trim();
  }

  // If user says "a healthy person", add "I am"
  if (!lower.startsWith('i am') && !lower.startsWith('i\'m')) {
    return `I am ${input.trim()}`;
  }

  return input.trim();
}

function normalizeHabitName(input: string): string {
  const lower = input.toLowerCase().trim();

  // Extract core habit from longer phrases
  // e.g., "I want to read more" → "Read every day"
  if (lower.includes('read')) {
    return 'Read every day';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Write in my journal';
  } else if (lower.includes('exercise') || lower.includes('workout')) {
    return 'Exercise';
  } else if (lower.includes('meditate')) {
    return 'Meditate';
  } else if (lower.includes('walk')) {
    return 'Go for a walk';
  } else if (lower.includes('run')) {
    return 'Go for a run';
  }

  return input.trim() || 'Build a new habit';
}

function generateTinyVersion(habitName: string): string {
  const lower = habitName.toLowerCase();

  if (lower.includes('read')) {
    return 'Read one page';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Write one sentence';
  } else if (lower.includes('exercise') || lower.includes('workout')) {
    return 'Do 5 pushups';
  } else if (lower.includes('meditate')) {
    return 'Meditate for 1 minute';
  } else if (lower.includes('walk')) {
    return 'Walk for 2 minutes';
  } else if (lower.includes('run')) {
    return 'Put on running shoes and step outside';
  }

  return `Start ${habitName.toLowerCase()} for 2 minutes`;
}

function normalizeTime(input: string): string {
  const lower = input.toLowerCase().trim();

  // Try to extract HH:MM format
  const timeMatch = input.match(/(\d{1,2}):(\d{2})/);
  if (timeMatch) {
    const hour = parseInt(timeMatch[1], 10);
    const minute = parseInt(timeMatch[2], 10);
    return `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
  }

  // Parse natural language time
  if (lower.includes('morning') || lower.includes('wake up') || lower.includes('breakfast')) {
    return '07:00';
  } else if (lower.includes('lunch') || lower.includes('noon') || lower.includes('midday')) {
    return '12:00';
  } else if (lower.includes('afternoon')) {
    return '15:00';
  } else if (lower.includes('evening') || lower.includes('dinner')) {
    return '18:00';
  } else if (lower.includes('night') || lower.includes('bed') || lower.includes('sleep')) {
    return '21:00';
  }

  // Default to evening
  return '19:00';
}

function normalizeLocation(input: string): string {
  const lower = input.toLowerCase().trim();

  if (!input || input.length < 2) {
    return 'At home';
  }

  // Add "at" or "in" if missing
  if (!lower.startsWith('at ') && !lower.startsWith('in ') && !lower.startsWith('on ')) {
    return `At ${input.trim()}`;
  }

  return input.trim();
}

function inferTemptationBundle(habitName: string, enjoyableContext: string, time: string): string | null {
  const lower = habitName.toLowerCase();
  const enjoyLower = enjoyableContext.toLowerCase();

  // If user mentioned something enjoyable, use it
  if (enjoyLower.includes('coffee') || enjoyLower.includes('tea')) {
    return `Have ${enjoyLower.includes('coffee') ? 'coffee' : 'tea'} while doing this`;
  }
  if (enjoyLower.includes('music')) {
    return 'Listen to your favorite music';
  }
  if (enjoyLower.includes('podcast')) {
    return 'Listen to a podcast';
  }

  // Default suggestions based on habit
  if (lower.includes('read')) {
    return time >= '18:00' ? 'Have herbal tea while reading' : 'Have coffee while reading';
  } else if (lower.includes('exercise') || lower.includes('walk')) {
    return 'Listen to your favorite podcast';
  } else if (lower.includes('write')) {
    return 'Light a candle and play soft music';
  }

  return null;
}

function inferPreHabitRitual(habitName: string): string | null {
  const lower = habitName.toLowerCase();

  if (lower.includes('read')) {
    return 'Take 3 deep breaths and open your book';
  } else if (lower.includes('write') || lower.includes('journal')) {
    return 'Put your phone on Do Not Disturb';
  } else if (lower.includes('exercise')) {
    return 'Put on your workout clothes immediately';
  } else if (lower.includes('meditate')) {
    return 'Close your eyes and take 3 deep breaths';
  }

  return 'Take 3 slow, deep breaths';
}

function inferEnvironmentCue(habitName: string, location: string, time: string): string | null {
  const lower = habitName.toLowerCase();
  const locationLower = location.toLowerCase();

  if (lower.includes('read')) {
    if (locationLower.includes('bed')) {
      return `Put your book on your pillow at ${time}`;
    }
    return 'Place your book where you can\'t miss it';
  } else if (lower.includes('exercise') || lower.includes('walk')) {
    return 'Lay out your workout clothes the night before';
  } else if (lower.includes('write')) {
    return 'Leave your journal open with a pen on top';
  }

  return `Place a visual reminder in ${location}`;
}

function inferEnvironmentDistraction(habitName: string): string | null {
  const lower = habitName.toLowerCase();

  if (lower.includes('read') || lower.includes('write') || lower.includes('meditate')) {
    return 'Charge your phone in another room';
  } else if (lower.includes('exercise')) {
    return 'Put your phone on Do Not Disturb mode';
  }

  return 'Put your phone in another room';
}

// ========== LLM INTEGRATION WITH FALLBACK ==========

/**
 * Generate onboarding habit plan using OpenAI LLM, with automatic fallback to heuristics
 *
 * Behavior:
 * 1. If OPENAI_API_KEY is not set → use heuristics immediately
 * 2. If OPENAI_API_KEY is set → try LLM with 5s timeout
 * 3. If LLM fails (network, timeout, invalid response) → fall back to heuristics
 *
 * Guarantees: Always returns a HabitPlanResult with at least basic fields
 */
export async function generateOnboardingHabitPlan(
  context: OnboardingCoachContext
): Promise<HabitPlanResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  // No API key → use heuristics immediately
  if (!apiKey) {
    console.warn('⚠️  OPENAI_API_KEY not set – using heuristic habit plan generation');
    return generateHeuristicHabitPlan(context);
  }

  // Try LLM with timeout
  try {
    console.log(`🤖 Attempting OpenAI LLM call for coach onboarding...`);

    const result = await Promise.race([
      callOpenAI(apiKey, context),
      createTimeout(5000, 'OpenAI request timeout after 5s')
    ]);

    // Validate LLM response
    if (result && result.habitPlan && result.habitPlan.habitName && result.habitPlan.tinyVersion) {
      console.log(`✅ OpenAI returned habit plan for "${result.habitPlan.habitName}"`);
      return result;
    } else {
      console.error('❌ OpenAI returned invalid habit plan structure, using fallback');
      return generateHeuristicHabitPlan(context);
    }
  } catch (error) {
    console.error('❌ OpenAI call failed:', error instanceof Error ? error.message : String(error));
    console.log('🔄 Falling back to heuristic habit plan generation');
    return generateHeuristicHabitPlan(context);
  }
}

/**
 * Call OpenAI API to generate habit plan from conversational context
 */
async function callOpenAI(
  apiKey: string,
  context: OnboardingCoachContext
): Promise<HabitPlanResult> {
  const openai = new OpenAI({ apiKey });

  // Build prompt
  const prompt = buildPrompt(context);

  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'system',
        content: `You are an Atomic Habits coach helping someone design their first tiny habit.

CORE PRINCIPLES:
1. Identity-first: Every habit starts with identity. Format: "I am a [type of person]" or "I am someone who [verb]"
2. 2-minute rule: The tiny version must be doable in 2 minutes or less, even on a bad day. Ritualize the beginning, not the outcome.
3. Four Laws of Behaviour Change:
   - Make it Obvious: implementation_time, implementation_location, environment_cue
   - Make it Attractive: temptation_bundle, pre_habit_ritual
   - Make it Easy: tiny_version must be low-friction
   - Make it Satisfying: the plan should feel achievable, not punishing

TONE:
- Short and concrete (no essays)
- Non-judgmental (no shaming, no overpromising)
- Realistic and encouraging

FIELD RULES:
- identity: Convert to "I am a [X]" format. Max 80 chars.
- habit_name: Short description of habit (not identity). Max 80 chars.
- tiny_version: <= 2 minutes. The very first step. Max 80 chars. REQUIRED.
- implementation_time: "HH:MM" 24h format. Parse from context or default: morning=07:00, afternoon=15:00, evening=21:00.
- implementation_location: Specific place. If unknown, use "At home" and add "location" to missing_fields.
- temptation_bundle: Pair with something enjoyable. Use context if available. Set null if nothing natural.
- pre_habit_ritual: 10-30 second action to start. Set null if nothing obvious.
- environment_cue: Visual cue 10-30 min before time. Set null if can't infer.
- environment_distraction: Realistic friction removal. Set null if nothing safe to infer.

CONFIDENCE SCORING:
- 0.80-0.95: Have identity, habit idea, and time/location with minimal guessing
- 0.60-0.79: Some elements inferred but reasonable
- 0.40-0.59: Had to guess key elements
- Never 1.0

MISSING_FIELDS:
Add human-readable tags for what user should double-check (e.g., "time", "location", "temptation_bundle")

NOTES:
1-2 short sentences explaining what to review. Tone: "This is a starting point; adjust anything that doesn't feel realistic."

Always respond with strict JSON only. No markdown, no extra keys.`
      },
      {
        role: 'user',
        content: prompt
      }
    ],
    temperature: 0.7,
    max_tokens: 600,
    response_format: { type: 'json_object' }
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error('OpenAI returned empty response');
  }

  // Parse and validate JSON
  const parsed = JSON.parse(content);

  if (!parsed.habit_plan) {
    throw new Error('OpenAI response missing "habit_plan" object');
  }

  const plan = parsed.habit_plan;

  // Validate required fields
  if (!plan.identity || !plan.habit_name || !plan.tiny_version ||
      !plan.implementation_time || !plan.implementation_location) {
    throw new Error('OpenAI habit plan missing required fields');
  }

  // Validate time format (HH:MM)
  if (!plan.implementation_time.match(/^\d{2}:\d{2}$/)) {
    throw new Error('Invalid implementation_time format (expected HH:MM)');
  }

  // Build metadata
  const missingFields: string[] = [];
  if (!plan.temptation_bundle) missingFields.push('temptation_bundle');
  if (!plan.pre_habit_ritual) missingFields.push('pre_habit_ritual');
  if (!plan.environment_cue) missingFields.push('environment_cue');
  if (!plan.environment_distraction) missingFields.push('environment_distraction');

  const metadata: HabitPlanMetadata = {
    confidence: parsed.metadata?.confidence || 0.85,
    missingFields: missingFields.length > 0 ? missingFields : undefined,
    notes: parsed.metadata?.notes || 'AI-generated plan. Review and adjust as needed.',
  };

  return {
    habitPlan: {
      identity: plan.identity.trim(),
      habitName: plan.habit_name.trim(),
      tinyVersion: plan.tiny_version.trim(),
      implementationTime: plan.implementation_time.trim(),
      implementationLocation: plan.implementation_location.trim(),
      temptationBundle: plan.temptation_bundle?.trim() || undefined,
      preHabitRitual: plan.pre_habit_ritual?.trim() || undefined,
      environmentCue: plan.environment_cue?.trim() || undefined,
      environmentDistraction: plan.environment_distraction?.trim() || undefined,
    },
    metadata,
  };
}

/**
 * Build the prompt for OpenAI coach onboarding
 */
function buildPrompt(context: OnboardingCoachContext): string {
  return `Design a tiny habit plan for ${context.userName || 'the user'} based on their answers.

CONVERSATION ANSWERS:

Q1: "Who are you trying to become?"
A: ${context.desiredIdentity || 'Not provided'}

Q2: "What habit would support that?"
A: ${context.habitIdea || 'Not provided'}

Q3: "When does this fit in your day?"
A: ${context.whenInDay || 'Not provided'}

Q4: "Where will you usually be?"
A: ${context.whereLocation || 'Not provided'}

Q5: "What makes it easier or more enjoyable?"
A: ${context.whatMakesItEnjoyable || 'Not provided'}

INSTRUCTIONS:
Generate a complete habit_plan following the Four Laws and 2-minute rule.

REQUIRED FIELDS:
1. identity: Convert to "I am a [type of person]" or "I am someone who [verb]". Max 80 chars.
   Examples: "I am a reader", "I am someone who moves every day"

2. habit_name: Short habit description (not the identity). Max 80 chars.
   Examples: "Read every day", "Go for a walk", "Write in my journal"

3. tiny_version: <= 2 minutes. The first step only, not the full habit. Max 80 chars. REQUIRED.
   Examples: "Read one page", "Put on trainers and walk to the end of the street", "Open journal and write one sentence"

4. implementation_time: "HH:MM" 24h format. Parse natural language:
   - "before bed around 9pm" → "21:00"
   - "morning" → "07:00", "afternoon" → "15:00", "evening" → "21:00"
   - If completely unknown → "20:00" and add "time" to missing_fields

5. implementation_location: Specific place. Max 60 chars.
   Examples: "In bed", "At my desk", "In the living room", "At the gym"
   If unknown → "At home" and add "location" to missing_fields

OPTIONAL FIELDS (set null if can't infer naturally):
6. temptation_bundle: Pair with something enjoyable from Q5. Max 80 chars.
   Examples: "Have herbal tea while reading", "Listen to favorite playlist while walking"

7. pre_habit_ritual: 10-30 second action to start. Max 80 chars.
   Examples: "Take 3 slow breaths and open book", "Fill a glass of water", "Put phone on Do Not Disturb"

8. environment_cue: Visual reminder 10-30 min before time. Max 80 chars.
   Examples: "Put book on pillow at 20:45", "Lay out trainers by the door at 06:45"

9. environment_distraction: Realistic friction to remove. Max 80 chars.
   Examples: "Charge phone in the kitchen", "Turn off TV before 21:00"
   Don't suggest extreme digital detox unless user strongly hints.

METADATA:
- confidence: 0.40-0.95 based on how much you had to guess. Never 1.0.
- missing_fields: Array of fields user should review (e.g., ["time", "location"])
- notes: 1-2 sentences. What should they double-check? Encouraging tone.

Return ONLY this JSON structure:
{
  "habit_plan": {
    "identity": "I am a reader",
    "habit_name": "Read every day",
    "tiny_version": "Read one page",
    "implementation_time": "21:00",
    "implementation_location": "In bed",
    "temptation_bundle": "Have herbal tea while reading",
    "pre_habit_ritual": "Take 3 deep breaths and open book",
    "environment_cue": "Put book on pillow at 20:45",
    "environment_distraction": "Charge phone in the kitchen"
  },
  "metadata": {
    "confidence": 0.85,
    "missing_fields": [],
    "notes": "This is a starting point. Adjust anything that doesn't feel realistic."
  }
}`;
}

/**
 * Create a timeout promise that rejects after specified milliseconds
 */
function createTimeout(ms: number, message: string): Promise<never> {
  return new Promise((_, reject) => {
    setTimeout(() => reject(new Error(message)), ms);
  });
}
