import 'package:hive/hive.dart';

part 'local_audio_record.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
class LocalAudioRecord extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String userAudioPath;
  
  @HiveField(2)
  final String? aiAudioPath;

  @HiveField(3)
  final int userAudioDurationMs;

  @HiveField(4)
  final int aiAudioDurationMs;

  @HiveField(5)
  final DateTime createdAt;

  @HiveField(6)
  final String conversationId;

  @HiveField(7)
  final bool isOnboarding;

  LocalAudioRecord({
    required this.id,
    required this.userAudioPath,
    this.aiAudioPath,
    required this.userAudioDurationMs,
    required this.aiAudioDurationMs,
    required this.createdAt,
    required this.conversationId,
    this.isOnboarding = false,
  });

  @override
  String toString() {
    return 'LocalAudioRecord(id: $id, userPath: $userAudioPath, aiPath: $aiAudioPath)';
  }
}
