// Mocks generated by Mockito 5.4.4 from annotations
// in atomic_habits_hook_app/test/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:atomic_habits_hook_app/data/models/habit.dart' as _i6;
import 'package:atomic_habits_hook_app/data/repositories/psychometric_repository.dart'
    as _i3;
import 'package:atomic_habits_hook_app/domain/entities/psychometric_profile.dart'
    as _i2;
import 'package:atomic_habits_hook_app/domain/services/psychometric_engine.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePsychometricProfile_0 extends _i1.SmartFake
    implements _i2.PsychometricProfile {
  _FakePsychometricProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PsychometricRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPsychometricRepository extends _i1.Mock
    implements _i3.PsychometricRepository {
  MockPsychometricRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.PsychometricProfile?> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.PsychometricProfile?>.value(),
      ) as _i4.Future<_i2.PsychometricProfile?>);

  @override
  _i4.Future<void> saveProfile(_i2.PsychometricProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsSynced() => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PsychometricEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockPsychometricEngine extends _i1.Mock
    implements _i5.PsychometricEngine {
  MockPsychometricEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PsychometricProfile onHabitMiss(_i2.PsychometricProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #onHabitMiss,
          [profile],
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #onHabitMiss,
            [profile],
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i2.PsychometricProfile onHabitComplete(
    _i2.PsychometricProfile? profile, {
    bool? wasRecovery = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #onHabitComplete,
          [profile],
          {#wasRecovery: wasRecovery},
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #onHabitComplete,
            [profile],
            {#wasRecovery: wasRecovery},
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i4.Future<_i2.PsychometricProfile> recalibrateRisksAsync(
    _i2.PsychometricProfile? profile,
    List<_i6.Habit>? habits,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recalibrateRisksAsync,
          [
            profile,
            habits,
          ],
        ),
        returnValue: _i4.Future<_i2.PsychometricProfile>.value(
            _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #recalibrateRisksAsync,
            [
              profile,
              habits,
            ],
          ),
        )),
      ) as _i4.Future<_i2.PsychometricProfile>);

  @override
  _i2.PsychometricProfile recalibrateRisksSync(
    _i2.PsychometricProfile? profile,
    List<_i6.Habit>? habits,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recalibrateRisksSync,
          [
            profile,
            habits,
          ],
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #recalibrateRisksSync,
            [
              profile,
              habits,
            ],
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i2.PsychometricProfile updateFromChatFeedback(
    _i2.PsychometricProfile? profile, {
    required String? userMessage,
    required bool? wasPositiveResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFromChatFeedback,
          [profile],
          {
            #userMessage: userMessage,
            #wasPositiveResponse: wasPositiveResponse,
          },
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #updateFromChatFeedback,
            [profile],
            {
              #userMessage: userMessage,
              #wasPositiveResponse: wasPositiveResponse,
            },
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i2.PsychometricProfile initializeFromOnboarding({
    required String? identity,
    required String? motivation,
    String? bigWhy,
    List<String>? fears,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeFromOnboarding,
          [],
          {
            #identity: identity,
            #motivation: motivation,
            #bigWhy: bigWhy,
            #fears: fears,
          },
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #initializeFromOnboarding,
            [],
            {
              #identity: identity,
              #motivation: motivation,
              #bigWhy: bigWhy,
              #fears: fears,
            },
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i2.PsychometricProfile updateFromSensorData(
    _i2.PsychometricProfile? profile, {
    int? sleepMinutes,
    double? hrv,
    int? distractionMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFromSensorData,
          [profile],
          {
            #sleepMinutes: sleepMinutes,
            #hrv: hrv,
            #distractionMinutes: distractionMinutes,
          },
        ),
        returnValue: _FakePsychometricProfile_0(
          this,
          Invocation.method(
            #updateFromSensorData,
            [profile],
            {
              #sleepMinutes: sleepMinutes,
              #hrv: hrv,
              #distractionMinutes: distractionMinutes,
            },
          ),
        ),
      ) as _i2.PsychometricProfile);

  @override
  _i4.Future<String> calculatePeakEnergyWindowAsync(List<_i6.Habit>? habits) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePeakEnergyWindowAsync,
          [habits],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #calculatePeakEnergyWindowAsync,
            [habits],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  String constructSherlockPrompt(
    _i2.PsychometricProfile? profile,
    String? identity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #constructSherlockPrompt,
          [
            profile,
            identity,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #constructSherlockPrompt,
            [
              profile,
              identity,
            ],
          ),
        ),
      ) as String);
}
